title: ALADIN Docs
author: Paul Christ

execute:
  execute_notebooks: "force"

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://HTW-ALADIN.github.io/documentation

repository:
  url: https://github.com/HTW-ALADIN/documentation
  branch: source

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

latex:
  latex_documents:
    targetname: aladin_docs.tex

parse:
  myst_enable_extensions:
    - html_image
    - dollarmath

bibtex_bibfiles:
  - bibliography.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false 
    latex_toplevel_sectioning: part
    latex_show_pagerefs: true
    latex_show_urls: 'footnote'
  extra_extensions:
    - sphinxcontrib.mermaid
    - sphinxcontrib.wavedrom


parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
